// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

type CaseStudyDocumentDataSlicesSlice = CaseStudyHeaderSlice | CaseStudyMetaSlice | TwoColumnCopySlice | CaseStudyGallerySlice | ThreeCardsSlice | TitledParagraphSlice | CaseStudyResultsSlice | CaseStudyFeedbackSlice

/**
 * Content for Case Study documents
 */
interface CaseStudyDocumentData {
	/**
	 * Client field in *Case Study*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: e.g. Evolus — shown as the small label on the /work listing card
	 * - **API ID Path**: case_study.client
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	client: prismic.KeyTextField;
	
	/**
	 * Title field in *Case Study*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Short display title — shown on the /work listing card. Separate from the case_study_header slice's own title so the listing page doesn't need to read into slice data.
	 * - **API ID Path**: case_study.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Listing image field in *Case Study*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.listing_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	listing_image: prismic.ImageField<never>;
	
	/**
	 * Slice Zone field in *Case Study*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<CaseStudyDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Case Study*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: case_study.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Case Study*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: case_study.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Case Study*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Case Study document from Prismic
 *
 * - **API ID**: `case_study`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudyDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<CaseStudyDocumentData>, "case_study", Lang>;

type HomeDocumentDataSlicesSlice = HeroSlice | ThreeCardsSlice | DeliveryTitleCtaSlice | OurServicesSlice | IndustriesSlice | StatsSectionSlice | ConnectWithUsSlice

/**
 * Content for Home documents
 */
interface HomeDocumentData {
	/**
	 * Meta Title field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Title used for search engines
	 * - **API ID Path**: home.meta_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Description used for search engines
	 * - **API ID Path**: home.meta_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *Home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice = HeroSlice | ThreeCardsSlice | DeliveryTitleCtaSlice | OurServicesSlice | IndustriesSlice | StatsSectionSlice | ConnectWithUsSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
	
	/**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Title used for search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Description used for search engines
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SettingsDocumentDataSlicesSlice = NavigationSlice | FooterSlice

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
	/**
	 * Favicon field in *Settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.favicon
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	favicon: prismic.ImageField<never>;
	
	/**
	 * Slice Zone field in *Settings*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;/**
	 * Head scripts field in *Settings*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Inline JS, run inside <head>. Paste the exact Google Tag Manager <script> snippet — the wrapping <script> tags are stripped automatically.
	 * - **API ID Path**: settings.head_scripts
	 * - **Tab**: Tracking Scripts
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	head_scripts: prismic.RichTextField;
	
	/**
	 * Body start scripts field in *Settings*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Pasted verbatim right after the opening <body> tag. e.g. the Google Tag Manager <noscript> snippet.
	 * - **API ID Path**: settings.body_start_scripts
	 * - **Tab**: Tracking Scripts
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body_start_scripts: prismic.RichTextField;
	
	/**
	 * Body end scripts field in *Settings*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Pasted verbatim right before the closing </body> tag.
	 * - **API ID Path**: settings.body_end_scripts
	 * - **Tab**: Tracking Scripts
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body_end_scripts: prismic.RichTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SettingsDocumentData>, "settings", Lang>;

type WorkDocumentDataSlicesSlice = PageHeadingSlice | CaseStudiesListSlice

/**
 * Content for Work documents
 */
interface WorkDocumentData {
	/**
	 * Slice Zone field in *Work*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<WorkDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: work.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: work.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Work*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<WorkDocumentData>, "work", Lang>;

export type AllDocumentTypes = CaseStudyDocument | HomeDocument | PageDocument | SettingsDocument | WorkDocument;

/**
 * Default variation for CaseStudiesList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudiesListSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, never>;

/**
 * Slice variation for *CaseStudiesList*
 */
type CaseStudiesListSliceVariation = CaseStudiesListSliceDefault

/**
 * CaseStudiesList Shared Slice
 *
 * - **API ID**: `case_studies_list`
 * - **Description**: CaseStudiesList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudiesListSlice = prismic.SharedSlice<"case_studies_list", CaseStudiesListSliceVariation>;

/**
 * Primary content in *CaseStudyFeedback → Default → Primary*
 */
export interface CaseStudyFeedbackSliceDefaultPrimary {
	/**
	 * Label field in *CaseStudyFeedback → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Feedback
	 * - **API ID Path**: case_study_feedback.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Quote field in *CaseStudyFeedback → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A short, impactful quote from the client.
	 * - **API ID Path**: case_study_feedback.default.primary.quote
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	quote: prismic.KeyTextField;
	
	/**
	 * Name field in *CaseStudyFeedback → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Jane Doe
	 * - **API ID Path**: case_study_feedback.default.primary.name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Description field in *CaseStudyFeedback → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Title, Company
	 * - **API ID Path**: case_study_feedback.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
}

/**
 * Default variation for CaseStudyFeedback Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyFeedbackSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CaseStudyFeedbackSliceDefaultPrimary>, never>;

/**
 * Slice variation for *CaseStudyFeedback*
 */
type CaseStudyFeedbackSliceVariation = CaseStudyFeedbackSliceDefault

/**
 * CaseStudyFeedback Shared Slice
 *
 * - **API ID**: `case_study_feedback`
 * - **Description**: CaseStudyFeedback
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyFeedbackSlice = prismic.SharedSlice<"case_study_feedback", CaseStudyFeedbackSliceVariation>;

/**
 * Primary content in *CaseStudyGallery → Items*
 */
export interface CaseStudyGallerySliceDefaultItem {
	/**
	 * Image field in *CaseStudyGallery → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study_gallery.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for CaseStudyGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyGallerySliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<CaseStudyGallerySliceDefaultItem>>;

/**
 * Slice variation for *CaseStudyGallery*
 */
type CaseStudyGallerySliceVariation = CaseStudyGallerySliceDefault

/**
 * CaseStudyGallery Shared Slice
 *
 * - **API ID**: `case_study_gallery`
 * - **Description**: CaseStudyGallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyGallerySlice = prismic.SharedSlice<"case_study_gallery", CaseStudyGallerySliceVariation>;

/**
 * Primary content in *CaseStudyHeader → Default → Primary*
 */
export interface CaseStudyHeaderSliceDefaultPrimary {
	/**
	 * Title field in *CaseStudyHeader → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: How Evolus transformed Medical Aesthetic
	 * - **API ID Path**: case_study_header.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Background image field in *CaseStudyHeader → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study_header.default.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	background_image: prismic.ImageField<never>;
}

/**
 * Default variation for CaseStudyHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyHeaderSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CaseStudyHeaderSliceDefaultPrimary>, never>;

/**
 * Slice variation for *CaseStudyHeader*
 */
type CaseStudyHeaderSliceVariation = CaseStudyHeaderSliceDefault

/**
 * CaseStudyHeader Shared Slice
 *
 * - **API ID**: `case_study_header`
 * - **Description**: CaseStudyHeader
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyHeaderSlice = prismic.SharedSlice<"case_study_header", CaseStudyHeaderSliceVariation>;

/**
 * Primary content in *CaseStudyMeta → Items*
 */
export interface CaseStudyMetaSliceDefaultItem {
	/**
	 * Label field in *CaseStudyMeta → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Client
	 * - **API ID Path**: case_study_meta.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Value field in *CaseStudyMeta → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Evolus
	 * - **API ID Path**: case_study_meta.items[].value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	value: prismic.KeyTextField;
}

/**
 * Default variation for CaseStudyMeta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyMetaSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<CaseStudyMetaSliceDefaultItem>>;

/**
 * Slice variation for *CaseStudyMeta*
 */
type CaseStudyMetaSliceVariation = CaseStudyMetaSliceDefault

/**
 * CaseStudyMeta Shared Slice
 *
 * - **API ID**: `case_study_meta`
 * - **Description**: CaseStudyMeta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyMetaSlice = prismic.SharedSlice<"case_study_meta", CaseStudyMetaSliceVariation>;

/**
 * Primary content in *CaseStudyResults → Items*
 */
export interface CaseStudyResultsSliceDefaultItem {
	/**
	 * Value field in *CaseStudyResults → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 100%
	 * - **API ID Path**: case_study_results.items[].value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	value: prismic.KeyTextField;
	
	/**
	 * Name field in *CaseStudyResults → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Increase in conversions
	 * - **API ID Path**: case_study_results.items[].name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Description field in *CaseStudyResults → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A short description of this metric
	 * - **API ID Path**: case_study_results.items[].description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
}

/**
 * Default variation for CaseStudyResults Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyResultsSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<CaseStudyResultsSliceDefaultItem>>;

/**
 * Slice variation for *CaseStudyResults*
 */
type CaseStudyResultsSliceVariation = CaseStudyResultsSliceDefault

/**
 * CaseStudyResults Shared Slice
 *
 * - **API ID**: `case_study_results`
 * - **Description**: CaseStudyResults
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyResultsSlice = prismic.SharedSlice<"case_study_results", CaseStudyResultsSliceVariation>;

/**
 * Primary content in *ConnectWithUs → Default → Primary*
 */
export interface ConnectWithUsSliceDefaultPrimary {
	/**
	 * Title field in *ConnectWithUs → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Connect with us to explore your project's potential.
	 * - **API ID Path**: connect_with_us.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Link field in *ConnectWithUs → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Where this banner should link to (optional)
	 * - **API ID Path**: connect_with_us.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for ConnectWithUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ConnectWithUsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ConnectWithUsSliceDefaultPrimary>, never>;

/**
 * Slice variation for *ConnectWithUs*
 */
type ConnectWithUsSliceVariation = ConnectWithUsSliceDefault

/**
 * ConnectWithUs Shared Slice
 *
 * - **API ID**: `connect_with_us`
 * - **Description**: ConnectWithUs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ConnectWithUsSlice = prismic.SharedSlice<"connect_with_us", ConnectWithUsSliceVariation>;

/**
 * Primary content in *DeliveryTitleCta → Default → Primary*
 */
export interface DeliveryTitleCtaSliceDefaultPrimary {
	/**
	 * Title field in *DeliveryTitleCta → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Success Stories
	 * - **API ID Path**: delivery_title_cta.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *DeliveryTitleCta → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: A short line introducing your work.
	 * - **API ID Path**: delivery_title_cta.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * CTA label field in *DeliveryTitleCta → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: View our work
	 * - **API ID Path**: delivery_title_cta.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * CTA link field in *DeliveryTitleCta → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Where the button should go
	 * - **API ID Path**: delivery_title_cta.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for DeliveryTitleCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DeliveryTitleCtaSliceDefault = prismic.SharedSliceVariation<"default", Simplify<DeliveryTitleCtaSliceDefaultPrimary>, never>;

/**
 * Slice variation for *DeliveryTitleCta*
 */
type DeliveryTitleCtaSliceVariation = DeliveryTitleCtaSliceDefault

/**
 * DeliveryTitleCta Shared Slice
 *
 * - **API ID**: `delivery_title_cta`
 * - **Description**: DeliveryTitleCta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DeliveryTitleCtaSlice = prismic.SharedSlice<"delivery_title_cta", DeliveryTitleCtaSliceVariation>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
	/**
	 * Office address field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: 9960 Irvine Center Dr
	Irvine, CA 92618
	 * - **API ID Path**: footer.default.primary.office_address
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	office_address: prismic.RichTextField;
	
	/**
	 * Phone label field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: (646) 555-4567
	 * - **API ID Path**: footer.default.primary.phone_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	phone_label: prismic.KeyTextField;
	
	/**
	 * Phone link field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: tel:+16465554567
	 * - **API ID Path**: footer.default.primary.phone_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	phone_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Email field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: hello@kingsmendv.com
	 * - **API ID Path**: footer.default.primary.email
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email: prismic.KeyTextField;
	
	/**
	 * Logo link field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Where the wordmark should link to
	 * - **API ID Path**: footer.default.primary.logo_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	logo_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Copyright text field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 2026 © All right reserved
	 * - **API ID Path**: footer.default.primary.copyright_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	copyright_text: prismic.KeyTextField;
	
	/**
	 * Privacy policy label field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Privacy Policy
	 * - **API ID Path**: footer.default.primary.privacy_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	privacy_label: prismic.KeyTextField;
	
	/**
	 * Privacy policy link field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.default.primary.privacy_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	privacy_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Footer → Items*
 */
export interface FooterSliceDefaultItem {
	/**
	 * Label field in *Footer → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: LinkedIn
	 * - **API ID Path**: footer.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Link field in *Footer → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<"default", Simplify<FooterSliceDefaultPrimary>, Simplify<FooterSliceDefaultItem>>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Heading field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: This is where it all begins
	 * - **API ID Path**: hero.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Subheading field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: A short supporting line under the headline
	 * - **API ID Path**: hero.default.primary.subheading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subheading: prismic.RichTextField;
	
	/**
	 * CTA label field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Get started
	 * - **API ID Path**: hero.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * CTA link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Where the button should go
	 * - **API ID Path**: hero.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Video file field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.video
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video: prismic.LinkToMediaField<prismic.FieldState, never>;
	
	/**
	 * Image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Industries → Default → Primary*
 */
export interface IndustriesSliceDefaultPrimary {
	/**
	 * Title field in *Industries → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Industries
	 * - **API ID Path**: industries.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
}

/**
 * Primary content in *Industries → Items*
 */
export interface IndustriesSliceDefaultItem {
	/**
	 * Label field in *Industries → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: List Label
	 * - **API ID Path**: industries.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
}

/**
 * Default variation for Industries Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndustriesSliceDefault = prismic.SharedSliceVariation<"default", Simplify<IndustriesSliceDefaultPrimary>, Simplify<IndustriesSliceDefaultItem>>;

/**
 * Slice variation for *Industries*
 */
type IndustriesSliceVariation = IndustriesSliceDefault

/**
 * Industries Shared Slice
 *
 * - **API ID**: `industries`
 * - **Description**: Industries
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndustriesSlice = prismic.SharedSlice<"industries", IndustriesSliceVariation>;

/**
 * Primary content in *Navigation → Default → Primary*
 */
export interface NavigationSliceDefaultPrimary {
	/**
	 * Logo link field in *Navigation → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: /
	 * - **API ID Path**: navigation.default.primary.logo_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	logo_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Navigation → Items*
 */
export interface NavigationSliceDefaultItem {
	/**
	 * Label field in *Navigation → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Work
	 * - **API ID Path**: navigation.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Link field in *Navigation → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Navigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationSliceDefault = prismic.SharedSliceVariation<"default", Simplify<NavigationSliceDefaultPrimary>, Simplify<NavigationSliceDefaultItem>>;

/**
 * Slice variation for *Navigation*
 */
type NavigationSliceVariation = NavigationSliceDefault

/**
 * Navigation Shared Slice
 *
 * - **API ID**: `navigation`
 * - **Description**: Navigation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationSlice = prismic.SharedSlice<"navigation", NavigationSliceVariation>;

/**
 * Primary content in *OurServices → Default → Primary*
 */
export interface OurServicesSliceDefaultPrimary {
	/**
	 * Title field in *OurServices → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Our Services
	 * - **API ID Path**: our_services.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * CTA label field in *OurServices → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Our Services
	 * - **API ID Path**: our_services.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * CTA link field in *OurServices → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Where the link should go
	 * - **API ID Path**: our_services.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *OurServices → Items*
 */
export interface OurServicesSliceDefaultItem {
	/**
	 * Category field in *OurServices → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Discovery
	 * - **API ID Path**: our_services.items[].category
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	category: prismic.KeyTextField;
	
	/**
	 * Label field in *OurServices → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: List Label
	 * - **API ID Path**: our_services.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
}

/**
 * Default variation for OurServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurServicesSliceDefault = prismic.SharedSliceVariation<"default", Simplify<OurServicesSliceDefaultPrimary>, Simplify<OurServicesSliceDefaultItem>>;

/**
 * Slice variation for *OurServices*
 */
type OurServicesSliceVariation = OurServicesSliceDefault

/**
 * OurServices Shared Slice
 *
 * - **API ID**: `our_services`
 * - **Description**: OurServices
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurServicesSlice = prismic.SharedSlice<"our_services", OurServicesSliceVariation>;

/**
 * Primary content in *PageHeading → Default → Primary*
 */
export interface PageHeadingSliceDefaultPrimary {
	/**
	 * Title field in *PageHeading → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Our work
	 * - **API ID Path**: page_heading.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
}

/**
 * Default variation for PageHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageHeadingSliceDefault = prismic.SharedSliceVariation<"default", Simplify<PageHeadingSliceDefaultPrimary>, never>;

/**
 * Slice variation for *PageHeading*
 */
type PageHeadingSliceVariation = PageHeadingSliceDefault

/**
 * PageHeading Shared Slice
 *
 * - **API ID**: `page_heading`
 * - **Description**: PageHeading
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageHeadingSlice = prismic.SharedSlice<"page_heading", PageHeadingSliceVariation>;

/**
 * Primary content in *StatsSection → Default → Primary*
 */
export interface StatsSectionSliceDefaultPrimary {
	/**
	 * Intro field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Frame & Form craft visual strategies that elevate your brand.
	 * - **API ID Path**: stats_section.default.primary.intro
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	intro: prismic.KeyTextField;
	
	/**
	 * Stat 1 value field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 1M+
	 * - **API ID Path**: stats_section.default.primary.stat_1_value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	stat_1_value: prismic.KeyTextField;
	
	/**
	 * Stat 1 label field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Users and visitors interacted with our websites
	 * - **API ID Path**: stats_section.default.primary.stat_1_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	stat_1_label: prismic.KeyTextField;
	
	/**
	 * Stat 2 value field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 36
	 * - **API ID Path**: stats_section.default.primary.stat_2_value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	stat_2_value: prismic.KeyTextField;
	
	/**
	 * Stat 2 label field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Active campaigns for multiple companies and brands
	 * - **API ID Path**: stats_section.default.primary.stat_2_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	stat_2_label: prismic.KeyTextField;
	
	/**
	 * Stat 3 value field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 100+
	 * - **API ID Path**: stats_section.default.primary.stat_3_value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	stat_3_value: prismic.KeyTextField;
	
	/**
	 * Stat 3 label field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Different clients have sought our expertise
	 * - **API ID Path**: stats_section.default.primary.stat_3_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	stat_3_label: prismic.KeyTextField;
	
	/**
	 * CTA label field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: About Us
	 * - **API ID Path**: stats_section.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * CTA link field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Where the link should go
	 * - **API ID Path**: stats_section.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *StatsSection → Items*
 */
export interface StatsSectionSliceDefaultItem {
	/**
	 * Badge image field in *StatsSection → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: stats_section.items[].badge_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	badge_image: prismic.ImageField<never>;
	
	/**
	 * Badge label field in *StatsSection → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Clutch — Top Design Company
	 * - **API ID Path**: stats_section.items[].badge_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	badge_label: prismic.KeyTextField;
}

/**
 * Default variation for StatsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsSectionSliceDefault = prismic.SharedSliceVariation<"default", Simplify<StatsSectionSliceDefaultPrimary>, Simplify<StatsSectionSliceDefaultItem>>;

/**
 * Slice variation for *StatsSection*
 */
type StatsSectionSliceVariation = StatsSectionSliceDefault

/**
 * StatsSection Shared Slice
 *
 * - **API ID**: `stats_section`
 * - **Description**: StatsSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsSectionSlice = prismic.SharedSlice<"stats_section", StatsSectionSliceVariation>;

/**
 * Primary content in *ThreeCards → Default → Primary*
 */
export interface ThreeCardsSliceDefaultPrimary {
	/**
	 * Label (optional) field in *ThreeCards → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Relevant cases
	 * - **API ID Path**: three_cards.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Content (optional) field in *ThreeCards → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Paragraph or two of intro copy shown above the cards
	 * - **API ID Path**: three_cards.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Primary content in *ThreeCards → Items*
 */
export interface ThreeCardsSliceDefaultItem {
	/**
	 * Image field in *ThreeCards → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: three_cards.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Title field in *ThreeCards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Title 1
	 * - **API ID Path**: three_cards.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Paragraph field in *ThreeCards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Paragraph 1
	 * - **API ID Path**: three_cards.items[].paragraph
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	paragraph: prismic.KeyTextField;
	
	/**
	 * Link label field in *ThreeCards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: See Project
	 * - **API ID Path**: three_cards.items[].link_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_label: prismic.KeyTextField;
	
	/**
	 * Link field in *ThreeCards → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: three_cards.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for ThreeCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ThreeCardsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ThreeCardsSliceDefaultPrimary>, Simplify<ThreeCardsSliceDefaultItem>>;

/**
 * Slice variation for *ThreeCards*
 */
type ThreeCardsSliceVariation = ThreeCardsSliceDefault

/**
 * ThreeCards Shared Slice
 *
 * - **API ID**: `three_cards`
 * - **Description**: ThreeCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ThreeCardsSlice = prismic.SharedSlice<"three_cards", ThreeCardsSliceVariation>;

/**
 * Primary content in *TitledParagraph → Default → Primary*
 */
export interface TitledParagraphSliceDefaultPrimary {
	/**
	 * Label field in *TitledParagraph → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Story
	 * - **API ID Path**: titled_paragraph.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Content field in *TitledParagraph → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Rich text
	 * - **API ID Path**: titled_paragraph.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for TitledParagraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TitledParagraphSliceDefault = prismic.SharedSliceVariation<"default", Simplify<TitledParagraphSliceDefaultPrimary>, never>;

/**
 * Slice variation for *TitledParagraph*
 */
type TitledParagraphSliceVariation = TitledParagraphSliceDefault

/**
 * TitledParagraph Shared Slice
 *
 * - **API ID**: `titled_paragraph`
 * - **Description**: TitledParagraph
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TitledParagraphSlice = prismic.SharedSlice<"titled_paragraph", TitledParagraphSliceVariation>;

/**
 * Primary content in *TwoColumnCopy → Items*
 */
export interface TwoColumnCopySliceDefaultItem {
	/**
	 * Label field in *TwoColumnCopy → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Challenge
	 * - **API ID Path**: two_column_copy.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Content field in *TwoColumnCopy → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Rich text
	 * - **API ID Path**: two_column_copy.items[].content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for TwoColumnCopy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColumnCopySliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<TwoColumnCopySliceDefaultItem>>;

/**
 * Slice variation for *TwoColumnCopy*
 */
type TwoColumnCopySliceVariation = TwoColumnCopySliceDefault

/**
 * TwoColumnCopy Shared Slice
 *
 * - **API ID**: `two_column_copy`
 * - **Description**: TwoColumnCopy
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColumnCopySlice = prismic.SharedSlice<"two_column_copy", TwoColumnCopySliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			CaseStudyDocument,
			CaseStudyDocumentData,
			CaseStudyDocumentDataSlicesSlice,
			HomeDocument,
			HomeDocumentData,
			HomeDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataSlicesSlice,
			WorkDocument,
			WorkDocumentData,
			WorkDocumentDataSlicesSlice,
			AllDocumentTypes,
			CaseStudiesListSlice,
			CaseStudiesListSliceVariation,
			CaseStudiesListSliceDefault,
			CaseStudyFeedbackSlice,
			CaseStudyFeedbackSliceDefaultPrimary,
			CaseStudyFeedbackSliceVariation,
			CaseStudyFeedbackSliceDefault,
			CaseStudyGallerySlice,
			CaseStudyGallerySliceDefaultItem,
			CaseStudyGallerySliceVariation,
			CaseStudyGallerySliceDefault,
			CaseStudyHeaderSlice,
			CaseStudyHeaderSliceDefaultPrimary,
			CaseStudyHeaderSliceVariation,
			CaseStudyHeaderSliceDefault,
			CaseStudyMetaSlice,
			CaseStudyMetaSliceDefaultItem,
			CaseStudyMetaSliceVariation,
			CaseStudyMetaSliceDefault,
			CaseStudyResultsSlice,
			CaseStudyResultsSliceDefaultItem,
			CaseStudyResultsSliceVariation,
			CaseStudyResultsSliceDefault,
			ConnectWithUsSlice,
			ConnectWithUsSliceDefaultPrimary,
			ConnectWithUsSliceVariation,
			ConnectWithUsSliceDefault,
			DeliveryTitleCtaSlice,
			DeliveryTitleCtaSliceDefaultPrimary,
			DeliveryTitleCtaSliceVariation,
			DeliveryTitleCtaSliceDefault,
			FooterSlice,
			FooterSliceDefaultPrimary,
			FooterSliceDefaultItem,
			FooterSliceVariation,
			FooterSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			IndustriesSlice,
			IndustriesSliceDefaultPrimary,
			IndustriesSliceDefaultItem,
			IndustriesSliceVariation,
			IndustriesSliceDefault,
			NavigationSlice,
			NavigationSliceDefaultPrimary,
			NavigationSliceDefaultItem,
			NavigationSliceVariation,
			NavigationSliceDefault,
			OurServicesSlice,
			OurServicesSliceDefaultPrimary,
			OurServicesSliceDefaultItem,
			OurServicesSliceVariation,
			OurServicesSliceDefault,
			PageHeadingSlice,
			PageHeadingSliceDefaultPrimary,
			PageHeadingSliceVariation,
			PageHeadingSliceDefault,
			StatsSectionSlice,
			StatsSectionSliceDefaultPrimary,
			StatsSectionSliceDefaultItem,
			StatsSectionSliceVariation,
			StatsSectionSliceDefault,
			ThreeCardsSlice,
			ThreeCardsSliceDefaultPrimary,
			ThreeCardsSliceDefaultItem,
			ThreeCardsSliceVariation,
			ThreeCardsSliceDefault,
			TitledParagraphSlice,
			TitledParagraphSliceDefaultPrimary,
			TitledParagraphSliceVariation,
			TitledParagraphSliceDefault,
			TwoColumnCopySlice,
			TwoColumnCopySliceDefaultItem,
			TwoColumnCopySliceVariation,
			TwoColumnCopySliceDefault
		}
	}
}