// Code generated by Slice Machine. DO NOT EDIT.
// This file is updated automatically every time you add, remove, or rename a
// slice in Slice Machine (see slicemachine.config.json -> libraries).

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  three_cards: dynamic(() => import("./ThreeCards")),
  delivery_title_cta: dynamic(() => import("./DeliveryTitleCta")),
  our_services: dynamic(() => import("./OurServices")),
  industries: dynamic(() => import("./Industries")),
  stats_section: dynamic(() => import("./StatsSection")),
  connect_with_us: dynamic(() => import("./ConnectWithUs")),
  navigation: dynamic(() => import("./Navigation")),
  footer: dynamic(() => import("./Footer")),
};
