// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

type HomeDocumentDataSlicesSlice = HeroSlice | ThreeCardsSlice | DeliveryTitleCtaSlice | OurServicesSlice | IndustriesSlice | StatsSectionSlice | ConnectWithUsSlice

/**
 * Content for Home documents
 */
interface HomeDocumentData {
	/**
	 * Meta Title field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Title used for search engines
	 * - **API ID Path**: home.meta_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Description used for search engines
	 * - **API ID Path**: home.meta_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *Home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice = HeroSlice | ThreeCardsSlice | DeliveryTitleCtaSlice | OurServicesSlice | IndustriesSlice | StatsSectionSlice | ConnectWithUsSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
	
	/**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Title used for search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Description used for search engines
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SettingsDocumentDataSlicesSlice = NavigationSlice | FooterSlice

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
	/**
	 * Favicon field in *Settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.favicon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	favicon: prismic.ImageField<never>;

	/**
	 * Head scripts field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pasted verbatim inside <head>. e.g. the Google Tag Manager <script> snippet.
	 * - **API ID Path**: settings.head_scripts
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	head_scripts: prismic.KeyTextField;

	/**
	 * Body start scripts field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pasted verbatim right after the opening <body> tag. e.g. the Google Tag Manager <noscript> snippet.
	 * - **API ID Path**: settings.body_start_scripts
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	body_start_scripts: prismic.KeyTextField;

	/**
	 * Body end scripts field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pasted verbatim right before the closing </body> tag.
	 * - **API ID Path**: settings.body_end_scripts
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	body_end_scripts: prismic.KeyTextField;

	/**
	 * Slice Zone field in *Settings*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SettingsDocumentData>, "settings", Lang>;

export type AllDocumentTypes = HomeDocument | PageDocument | SettingsDocument;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
	/**
	 * Office address field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: 9960 Irvine Center Dr
	Irvine, CA 92618
	 * - **API ID Path**: footer.default.primary.office_address
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	office_address: prismic.RichTextField;
	
	/**
	 * Phone label field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: (646) 555-4567
	 * - **API ID Path**: footer.default.primary.phone_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	phone_label: prismic.KeyTextField;
	
	/**
	 * Phone link field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: tel:+16465554567
	 * - **API ID Path**: footer.default.primary.phone_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	phone_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Email field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: hello@kingsmendv.com
	 * - **API ID Path**: footer.default.primary.email
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email: prismic.KeyTextField;
	
	/**
	 * Logo link field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Where the wordmark should link to
	 * - **API ID Path**: footer.default.primary.logo_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	logo_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Copyright text field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 2026 © All right reserved
	 * - **API ID Path**: footer.default.primary.copyright_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	copyright_text: prismic.KeyTextField;
	
	/**
	 * Privacy policy label field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Privacy Policy
	 * - **API ID Path**: footer.default.primary.privacy_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	privacy_label: prismic.KeyTextField;
	
	/**
	 * Privacy policy link field in *Footer → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.default.primary.privacy_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	privacy_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Footer → Items*
 */
export interface FooterSliceDefaultItem {
	/**
	 * Label field in *Footer → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: LinkedIn
	 * - **API ID Path**: footer.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Link field in *Footer → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<"default", Simplify<FooterSliceDefaultPrimary>, Simplify<FooterSliceDefaultItem>>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Heading field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: This is where it all begins
	 * - **API ID Path**: hero.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Subheading field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: A short supporting line under the headline
	 * - **API ID Path**: hero.default.primary.subheading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subheading: prismic.RichTextField;
	
	/**
	 * CTA label field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Get started
	 * - **API ID Path**: hero.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * CTA link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Where the button should go
	 * - **API ID Path**: hero.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Video file field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.video
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video: prismic.LinkToMediaField<prismic.FieldState, never>;
	
	/**
	 * Image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Navigation → Default → Primary*
 */
export interface NavigationSliceDefaultPrimary {
	/**
	 * Logo link field in *Navigation → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: /
	 * - **API ID Path**: navigation.default.primary.logo_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	logo_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Navigation → Items*
 */
export interface NavigationSliceDefaultItem {
	/**
	 * Label field in *Navigation → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Work
	 * - **API ID Path**: navigation.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;

	/**
	 * Link field in *Navigation → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Navigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationSliceDefault = prismic.SharedSliceVariation<"default", Simplify<NavigationSliceDefaultPrimary>, Simplify<NavigationSliceDefaultItem>>;

/**
 * Slice variation for *Navigation*
 */
type NavigationSliceVariation = NavigationSliceDefault

/**
 * Navigation Shared Slice
 *
 * - **API ID**: `navigation`
 * - **Description**: Navigation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationSlice = prismic.SharedSlice<"navigation", NavigationSliceVariation>;

/**
 * Primary content in *ThreeCards → Items*
 */
export interface ThreeCardsSliceDefaultItem {
	/**
	 * Image field in *ThreeCards → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: three_cards.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Title field in *ThreeCards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Title 1
	 * - **API ID Path**: three_cards.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Paragraph field in *ThreeCards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Paragraph 1
	 * - **API ID Path**: three_cards.items[].paragraph
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	paragraph: prismic.KeyTextField;

	/**
	 * Link label field in *ThreeCards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: See Project
	 * - **API ID Path**: three_cards.items[].link_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_label: prismic.KeyTextField;

	/**
	 * Link field in *ThreeCards → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: three_cards.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for ThreeCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ThreeCardsSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<ThreeCardsSliceDefaultItem>>;

/**
 * Slice variation for *ThreeCards*
 */
type ThreeCardsSliceVariation = ThreeCardsSliceDefault

/**
 * ThreeCards Shared Slice
 *
 * - **API ID**: `three_cards`
 * - **Description**: ThreeCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ThreeCardsSlice = prismic.SharedSlice<"three_cards", ThreeCardsSliceVariation>;

/**
 * Primary content in *DeliveryTitleCta → Default → Primary*
 */
export interface DeliveryTitleCtaSliceDefaultPrimary {
	/**
	 * Title field in *DeliveryTitleCta → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Success Stories
	 * - **API ID Path**: delivery_title_cta.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *DeliveryTitleCta → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: A short line introducing your work.
	 * - **API ID Path**: delivery_title_cta.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * CTA label field in *DeliveryTitleCta → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: View our work
	 * - **API ID Path**: delivery_title_cta.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;

	/**
	 * CTA link field in *DeliveryTitleCta → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Where the button should go
	 * - **API ID Path**: delivery_title_cta.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for DeliveryTitleCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DeliveryTitleCtaSliceDefault = prismic.SharedSliceVariation<"default", Simplify<DeliveryTitleCtaSliceDefaultPrimary>, never>;

/**
 * Slice variation for *DeliveryTitleCta*
 */
type DeliveryTitleCtaSliceVariation = DeliveryTitleCtaSliceDefault

/**
 * DeliveryTitleCta Shared Slice
 *
 * - **API ID**: `delivery_title_cta`
 * - **Description**: DeliveryTitleCta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DeliveryTitleCtaSlice = prismic.SharedSlice<"delivery_title_cta", DeliveryTitleCtaSliceVariation>;

/**
 * Primary content in *OurServices → Default → Primary*
 */
export interface OurServicesSliceDefaultPrimary {
	/**
	 * Title field in *OurServices → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Our Services
	 * - **API ID Path**: our_services.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * CTA label field in *OurServices → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Our Services
	 * - **API ID Path**: our_services.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;

	/**
	 * CTA link field in *OurServices → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Where the link should go
	 * - **API ID Path**: our_services.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *OurServices → Items*
 */
export interface OurServicesSliceDefaultItem {
	/**
	 * Category field in *OurServices → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Discovery
	 * - **API ID Path**: our_services.items[].category
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	category: prismic.KeyTextField;

	/**
	 * Label field in *OurServices → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: List Label
	 * - **API ID Path**: our_services.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
}

/**
 * Default variation for OurServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurServicesSliceDefault = prismic.SharedSliceVariation<"default", Simplify<OurServicesSliceDefaultPrimary>, Simplify<OurServicesSliceDefaultItem>>;

/**
 * Slice variation for *OurServices*
 */
type OurServicesSliceVariation = OurServicesSliceDefault

/**
 * OurServices Shared Slice
 *
 * - **API ID**: `our_services`
 * - **Description**: OurServices
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurServicesSlice = prismic.SharedSlice<"our_services", OurServicesSliceVariation>;

/**
 * Primary content in *Industries → Default → Primary*
 */
export interface IndustriesSliceDefaultPrimary {
	/**
	 * Title field in *Industries → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Industries
	 * - **API ID Path**: industries.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
}

/**
 * Primary content in *Industries → Items*
 */
export interface IndustriesSliceDefaultItem {
	/**
	 * Label field in *Industries → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: List Label
	 * - **API ID Path**: industries.items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
}

/**
 * Default variation for Industries Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndustriesSliceDefault = prismic.SharedSliceVariation<"default", Simplify<IndustriesSliceDefaultPrimary>, Simplify<IndustriesSliceDefaultItem>>;

/**
 * Slice variation for *Industries*
 */
type IndustriesSliceVariation = IndustriesSliceDefault

/**
 * Industries Shared Slice
 *
 * - **API ID**: `industries`
 * - **Description**: Industries
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndustriesSlice = prismic.SharedSlice<"industries", IndustriesSliceVariation>;

/**
 * Primary content in *StatsSection → Default → Primary*
 */
export interface StatsSectionSliceDefaultPrimary {
	/**
	 * Intro field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Frame & Form craft visual strategies that elevate your brand.
	 * - **API ID Path**: stats_section.default.primary.intro
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	intro: prismic.KeyTextField;

	/**
	 * Stat 1 value field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 1M+
	 * - **API ID Path**: stats_section.default.primary.stat_1_value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	stat_1_value: prismic.KeyTextField;

	/**
	 * Stat 1 label field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Users and visitors interacted with our websites
	 * - **API ID Path**: stats_section.default.primary.stat_1_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	stat_1_label: prismic.KeyTextField;

	/**
	 * Stat 2 value field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 36
	 * - **API ID Path**: stats_section.default.primary.stat_2_value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	stat_2_value: prismic.KeyTextField;

	/**
	 * Stat 2 label field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Active campaigns for multiple companies and brands
	 * - **API ID Path**: stats_section.default.primary.stat_2_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	stat_2_label: prismic.KeyTextField;

	/**
	 * Stat 3 value field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 100+
	 * - **API ID Path**: stats_section.default.primary.stat_3_value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	stat_3_value: prismic.KeyTextField;

	/**
	 * Stat 3 label field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Different clients have sought our expertise
	 * - **API ID Path**: stats_section.default.primary.stat_3_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	stat_3_label: prismic.KeyTextField;

	/**
	 * CTA label field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: About Us
	 * - **API ID Path**: stats_section.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;

	/**
	 * CTA link field in *StatsSection → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Where the link should go
	 * - **API ID Path**: stats_section.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *StatsSection → Items*
 */
export interface StatsSectionSliceDefaultItem {
	/**
	 * Badge image field in *StatsSection → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: stats_section.items[].badge_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	badge_image: prismic.ImageField<never>;

	/**
	 * Badge label field in *StatsSection → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Clutch — Top Design Company
	 * - **API ID Path**: stats_section.items[].badge_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	badge_label: prismic.KeyTextField;
}

/**
 * Default variation for StatsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsSectionSliceDefault = prismic.SharedSliceVariation<"default", Simplify<StatsSectionSliceDefaultPrimary>, Simplify<StatsSectionSliceDefaultItem>>;

/**
 * Slice variation for *StatsSection*
 */
type StatsSectionSliceVariation = StatsSectionSliceDefault

/**
 * StatsSection Shared Slice
 *
 * - **API ID**: `stats_section`
 * - **Description**: StatsSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsSectionSlice = prismic.SharedSlice<"stats_section", StatsSectionSliceVariation>;

/**
 * Primary content in *ConnectWithUs → Default → Primary*
 */
export interface ConnectWithUsSliceDefaultPrimary {
	/**
	 * Title field in *ConnectWithUs → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Connect with us to explore your project's potential.
	 * - **API ID Path**: connect_with_us.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Link field in *ConnectWithUs → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Where this banner should link to (optional)
	 * - **API ID Path**: connect_with_us.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for ConnectWithUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ConnectWithUsSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ConnectWithUsSliceDefaultPrimary>, never>;

/**
 * Slice variation for *ConnectWithUs*
 */
type ConnectWithUsSliceVariation = ConnectWithUsSliceDefault

/**
 * ConnectWithUs Shared Slice
 *
 * - **API ID**: `connect_with_us`
 * - **Description**: ConnectWithUs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ConnectWithUsSlice = prismic.SharedSlice<"connect_with_us", ConnectWithUsSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			HomeDocument,
			HomeDocumentData,
			HomeDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataSlicesSlice,
			AllDocumentTypes,
			FooterSlice,
			FooterSliceDefaultPrimary,
			FooterSliceDefaultItem,
			FooterSliceVariation,
			FooterSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			NavigationSlice,
			NavigationSliceDefaultPrimary,
			NavigationSliceDefaultItem,
			NavigationSliceVariation,
			NavigationSliceDefault,
			ThreeCardsSlice,
			ThreeCardsSliceDefaultItem,
			ThreeCardsSliceVariation,
			ThreeCardsSliceDefault,
			DeliveryTitleCtaSlice,
			DeliveryTitleCtaSliceDefaultPrimary,
			DeliveryTitleCtaSliceVariation,
			DeliveryTitleCtaSliceDefault,
			OurServicesSlice,
			OurServicesSliceDefaultPrimary,
			OurServicesSliceDefaultItem,
			OurServicesSliceVariation,
			OurServicesSliceDefault,
			IndustriesSlice,
			IndustriesSliceDefaultPrimary,
			IndustriesSliceDefaultItem,
			IndustriesSliceVariation,
			IndustriesSliceDefault,
			StatsSectionSlice,
			StatsSectionSliceDefaultPrimary,
			StatsSectionSliceDefaultItem,
			StatsSectionSliceVariation,
			StatsSectionSliceDefault,
			ConnectWithUsSlice,
			ConnectWithUsSliceDefaultPrimary,
			ConnectWithUsSliceVariation,
			ConnectWithUsSliceDefault
		}
	}
}